// Deterministic parenting-tips selector. Replaces the parenting_tips slice
// of the dashboard AI prompt (was generated by getParentDashboardPrompt and
// returned by generateParentDashboardInsights).
//
// Selection model
// ---------------
// Each tip carries a list of "signals". A signal fires when the student's
// current data crosses a threshold (low attendance, weak average, pending
// homework backlog, upcoming tests, etc.). Tips matching the active signals
// are ranked by signal-priority, then by stable hash of tip text so the
// list stays stable across renders for the same data.
//
// We always reserve at least one slot for an evergreen tip (sleep / reading)
// so a student with perfect data still sees actionable guidance.

export type ParentingTip = { tip: string; reason: string };

type Signal =
  | "attendance_low"      // < 75
  | "attendance_mid"      // 75..84
  | "attendance_high"     // >= 85
  | "score_low"           // 1..59
  | "score_mid"           // 60..79
  | "score_high"          // >= 80
  | "pending_heavy"       // > 3
  | "pending_some"        // 1..3
  | "pending_clear"       // 0
  | "tests_upcoming"      // > 0
  | "grade_primary"       // 1..5
  | "grade_middle"        // 6..8
  | "grade_senior"        // 9..12
  | "evergreen";          // always eligible

type CuratedTip = ParentingTip & {
  signals: Signal[];
  priority: number;       // higher wins ties
};

export type ParentingTipInput = {
  attendance: number | null;
  avgScore: number;       // 0 if unknown
  pending: number | null;
  tests: number | null;
  childName: string;
  grade?: string | number | null;
};

const N = (name: string) => (name && name.trim().length > 0 ? name.trim() : "your child");

// 50 curated tips. Tone: warm, specific, actionable. No invented numbers —
// the signal that triggers a tip is what supplies the data point.
const TIPS: CuratedTip[] = [
  // ── Attendance ─────────────────────────────────────────────────────────
  { tip: "Make school attendance a top priority this month", reason: "Attendance has slipped below 75% — every additional absence widens gaps that are hard to close mid-term.", signals: ["attendance_low"], priority: 95 },
  { tip: "Build a fixed wake-up and leave-by time on school nights", reason: "A predictable morning routine is the single biggest lever for fixing low attendance without daily friction.", signals: ["attendance_low"], priority: 90 },
  { tip: "Sit with the school office to plan make-up notes for missed lessons", reason: "After a stretch of absences, recovery work has to be deliberate — drifting back rarely catches the gaps.", signals: ["attendance_low"], priority: 80 },
  { tip: "Track attendance weekly with a simple wall chart at home", reason: "Attendance is in the 75–85% band — visible tracking nudges it past 90% within a few weeks.", signals: ["attendance_mid"], priority: 70 },
  { tip: "Identify which weekday is most often missed and plan around it", reason: "Mid-band attendance usually has a pattern; isolating the soft day fixes most of the dip.", signals: ["attendance_mid"], priority: 65 },
  { tip: "Acknowledge the strong attendance habit out loud this week", reason: "Above-85% attendance is a real achievement — naming it reinforces the routine for the rest of the term.", signals: ["attendance_high"], priority: 40 },

  // ── Academic performance ───────────────────────────────────────────────
  { tip: "Pick the two lowest-scoring subjects and rebuild the basics first", reason: "Average is below 60% — chasing every subject at once spreads effort thin; foundations come first.", signals: ["score_low"], priority: 95 },
  { tip: "Schedule a focused 30-minute revision block daily, same time slot", reason: "Below-60% averages respond best to short, repeatable sessions — not weekend marathons.", signals: ["score_low"], priority: 92 },
  { tip: "Ask the class teacher for the topic list to re-cover this term", reason: "A teacher-prioritised list beats guessing at where the gaps actually are.", signals: ["score_low"], priority: 85 },
  { tip: "Move from re-reading notes to attempting practice questions", reason: "Mid-band scores almost always improve when the study mode shifts from passive to active.", signals: ["score_mid"], priority: 75 },
  { tip: "Pick one weak chapter and master it end-to-end this week", reason: "At 60–80% average, depth on one topic lifts overall confidence faster than breadth across many.", signals: ["score_mid"], priority: 70 },
  { tip: "Review every wrong answer from the last test together", reason: "In the 60–80% band, the cheapest gains come from understanding mistakes already made.", signals: ["score_mid"], priority: 65 },
  { tip: "Introduce one stretch problem per subject each week", reason: "An 80%+ average means the standard syllabus is comfortable — variety keeps the mind sharp.", signals: ["score_high"], priority: 50 },
  { tip: "Encourage teaching a younger sibling or friend a recent topic", reason: "At top-band performance, explaining is the fastest way to convert good into excellent.", signals: ["score_high"], priority: 45 },
  { tip: "Look into one olympiad or enrichment track aligned with the strongest subject", reason: "Sustained 80%+ deserves a stretch goal so motivation stays high.", signals: ["score_high"], priority: 40 },

  // ── Homework backlog ──────────────────────────────────────────────────
  { tip: "Sit together tonight and list every pending assignment with due dates", reason: "There are more than 3 assignments outstanding — visibility is step one to clearing the backlog.", signals: ["pending_heavy"], priority: 90 },
  { tip: "Set a 25-minute homework sprint immediately after returning from school", reason: "A heavy pending list rarely clears by evening; the sprint anchors the day's first win.", signals: ["pending_heavy"], priority: 85 },
  { tip: "Pause weekend screen time until the backlog drops below two items", reason: "Heavy backlogs need a hard reset — a temporary boundary is fairer than nightly negotiation.", signals: ["pending_heavy"], priority: 75 },
  { tip: "Block 20 minutes after dinner to finish the pending homework", reason: "A small list is best cleared the same day so it doesn't snowball into a heavy backlog.", signals: ["pending_some"], priority: 60 },
  { tip: "Praise the clean homework slate at dinner tonight", reason: "Zero pending assignments is worth marking — recognition makes the habit stick.", signals: ["pending_clear"], priority: 35 },

  // ── Upcoming tests ─────────────────────────────────────────────────────
  { tip: "Build a three-day preparation plan for each upcoming test", reason: "Tests are coming up this week — spaced prep beats last-night cramming on retention.", signals: ["tests_upcoming"], priority: 88 },
  { tip: "Run a mock test at home over the weekend", reason: "A timed home attempt surfaces blind spots while there's still time to fix them.", signals: ["tests_upcoming"], priority: 80 },
  { tip: "Make sure the night-before-test routine includes early sleep, not extra revision", reason: "Sleep before a test contributes more to recall than the last hour of cramming.", signals: ["tests_upcoming"], priority: 78 },
  { tip: "Double-check the test syllabus directly with the school diary", reason: "A wrong assumption about scope is the easiest preventable cause of a poor test score.", signals: ["tests_upcoming"], priority: 65 },

  // ── Grade-stage targeted ──────────────────────────────────────────────
  { tip: "Read aloud together for 15 minutes every evening", reason: "Reading aloud at this stage builds vocabulary and listening comprehension faster than any worksheet.", signals: ["grade_primary"], priority: 55 },
  { tip: "Use real-world counting and money problems during shopping or cooking", reason: "Numeracy at the primary stage sticks best when tied to tangible everyday situations.", signals: ["grade_primary"], priority: 50 },
  { tip: "Limit unsupervised screen time to one defined slot per day", reason: "Habit boundaries set in the primary years are far easier than reversing them later.", signals: ["grade_primary"], priority: 45 },
  { tip: "Introduce a weekly review of notebooks together", reason: "Middle-school workload jumps quickly — a weekly check catches drift before it becomes a problem.", signals: ["grade_middle"], priority: 55 },
  { tip: "Help map subjects to a simple weekly study timetable on paper", reason: "Self-management is the core skill of middle school; a written timetable trains it without nagging.", signals: ["grade_middle"], priority: 50 },
  { tip: "Discuss long-term subject interests once a month, no pressure", reason: "Senior-stage choices are around the corner — early conversations widen options later.", signals: ["grade_senior"], priority: 50 },
  { tip: "Encourage one mock board paper per month from the strongest subject", reason: "Confidence with exam format matters as much as content at the senior stage.", signals: ["grade_senior"], priority: 48 },
  { tip: "Treat wellbeing check-ins as part of the study plan, not optional", reason: "Senior-stage academic load makes burnout the silent risk to grades.", signals: ["grade_senior"], priority: 45 },

  // ── Evergreen (always eligible) ────────────────────────────────────────
  { tip: "Ensure 8–9 hours of sleep on school nights", reason: "Sleep is when memory is consolidated — well-rested students learn faster the next day.", signals: ["evergreen"], priority: 30 },
  { tip: "Keep a 20-minute reading habit going every day", reason: "Daily reading lifts vocabulary, comprehension and writing across every subject.", signals: ["evergreen"], priority: 28 },
  { tip: "Eat a real breakfast before school, every day", reason: "Skipped breakfasts are linked to lower morning focus and weaker test performance.", signals: ["evergreen"], priority: 26 },
  { tip: "Reserve one screen-free hour before bedtime", reason: "Pre-bed screens delay sleep onset and reduce sleep quality, both of which hit next-day learning.", signals: ["evergreen"], priority: 25 },
  { tip: "Ask one open question about the school day at dinner", reason: "Daily, low-pressure conversation about school is the best early-warning system parents have.", signals: ["evergreen"], priority: 24 },
  { tip: "Keep the study desk free of phone notifications", reason: "A single notification fragments a study block; removing them is a free productivity gain.", signals: ["evergreen"], priority: 22 },
  { tip: "Build a 5-minute end-of-day reflection: one win, one struggle", reason: "A short reflection trains self-awareness, which is the foundation of independent learning.", signals: ["evergreen"], priority: 20 },
  { tip: "Schedule one outdoor activity slot every week", reason: "Physical activity directly supports attention span and stress regulation in school.", signals: ["evergreen"], priority: 18 },
  { tip: "Set up a quiet, well-lit fixed study spot at home", reason: "A dedicated space cues focus faster than studying wherever there is room.", signals: ["evergreen"], priority: 17 },
  { tip: "Praise effort and process more often than results", reason: "Effort-praise has been shown to build long-term resilience across grades and subjects.", signals: ["evergreen"], priority: 16 },
  { tip: "Keep a weekly 10-minute parent–child progress chat", reason: "A predictable check-in surfaces problems before they show up on a report card.", signals: ["evergreen"], priority: 15 },
  { tip: "Encourage handwritten summaries instead of highlighting", reason: "Writing in own words forces understanding; highlighting often masks it.", signals: ["evergreen"], priority: 14 },
  { tip: "Limit caffeinated drinks on school days", reason: "Hidden caffeine in colas and energy drinks disrupts sleep and concentration.", signals: ["evergreen"], priority: 13 },
  { tip: "Keep school stationery stocked and accessible", reason: "Small friction — missing pens, broken pencils — adds up to lost minutes every week.", signals: ["evergreen"], priority: 12 },
  { tip: "Encourage asking the teacher one question every day", reason: "Question-asking is the single best classroom habit and it has to be practised.", signals: ["evergreen"], priority: 11 },
  { tip: "Celebrate finishing a tough chapter together", reason: "Marking small completions builds the motivation to start the next one.", signals: ["evergreen"], priority: 10 },
];

const collectSignals = (input: ParentingTipInput): Set<Signal> => {
  const sigs = new Set<Signal>(["evergreen"]);

  if (input.attendance !== null) {
    if (input.attendance < 75) sigs.add("attendance_low");
    else if (input.attendance < 85) sigs.add("attendance_mid");
    else sigs.add("attendance_high");
  }

  if (input.avgScore > 0) {
    if (input.avgScore < 60) sigs.add("score_low");
    else if (input.avgScore < 80) sigs.add("score_mid");
    else sigs.add("score_high");
  }

  if (input.pending !== null) {
    if (input.pending > 3) sigs.add("pending_heavy");
    else if (input.pending >= 1) sigs.add("pending_some");
    else sigs.add("pending_clear");
  }

  if ((input.tests ?? 0) > 0) sigs.add("tests_upcoming");

  const gradeNum = typeof input.grade === "number"
    ? input.grade
    : parseInt(String(input.grade ?? "").replace(/\D+/g, ""), 10);
  if (Number.isFinite(gradeNum) && gradeNum > 0) {
    if (gradeNum <= 5) sigs.add("grade_primary");
    else if (gradeNum <= 8) sigs.add("grade_middle");
    else sigs.add("grade_senior");
  }

  return sigs;
};

const personaliseTip = (tip: string, name: string): string => {
  // Insert the child's name where it reads naturally; otherwise leave alone.
  if (tip.includes("the strong attendance habit")) return `Acknowledge ${name}'s strong attendance habit out loud this week`;
  if (tip.includes("Sit together tonight")) return `Sit with ${name} tonight and list every pending assignment with due dates`;
  if (tip.includes("Sit with the school office")) return `Sit with the school office to plan make-up notes for ${name}'s missed lessons`;
  if (tip.includes("revision block daily")) return `Schedule a focused 30-minute revision block for ${name} daily, same time slot`;
  if (tip.includes("Run a mock test at home")) return `Run a mock test for ${name} at home over the weekend`;
  if (tip.includes("Read aloud together")) return `Read aloud with ${name} for 15 minutes every evening`;
  if (tip.includes("Praise the clean homework")) return `Praise ${name}'s clean homework slate at dinner tonight`;
  return tip;
};

export function selectParentingTips(input: ParentingTipInput, count = 3): ParentingTip[] {
  const name = N(input.childName);
  const signals = collectSignals(input);

  const eligible = TIPS
    .filter((t) => t.signals.some((s) => signals.has(s)))
    .map((t) => ({ ...t, score: t.priority }));

  // Stable secondary sort: hash of tip text, so a tie in priority still
  // produces a deterministic order and the list doesn't reshuffle on every
  // render for the same input.
  const hash = (s: string): number => {
    let h = 0;
    for (let i = 0; i < s.length; i++) h = ((h << 5) - h + s.charCodeAt(i)) | 0;
    return h;
  };

  eligible.sort((a, b) => (b.score - a.score) || (hash(a.tip) - hash(b.tip)));

  // Diversity pass — avoid emitting two tips that both fire on the same
  // top signal (e.g. two attendance_low tips back-to-back). We pick the
  // highest-priority tip per signal first, then top up from the pool.
  const picked: CuratedTip[] = [];
  const usedPrimary = new Set<Signal>();

  for (const t of eligible) {
    if (picked.length >= count) break;
    const primary = t.signals.find((s) => signals.has(s) && s !== "evergreen") ?? "evergreen";
    if (usedPrimary.has(primary) && primary !== "evergreen") continue;
    picked.push(t);
    usedPrimary.add(primary);
  }

  // If still under count, top up ignoring the diversity rule.
  if (picked.length < count) {
    for (const t of eligible) {
      if (picked.length >= count) break;
      if (!picked.includes(t)) picked.push(t);
    }
  }

  return picked.slice(0, count).map((t) => ({
    tip: personaliseTip(t.tip, name),
    reason: t.reason,
  }));
}
